services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: pizzashop-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=pizzashop
    volumes:
      - pizza_shop_pg_data:/bitnami/postgresql

volumes:
  pizza_shop_pg_data:
  